db-uri = "postgres://USER:PASSWORD@HOST:PORT/DBNAME"
db-schema = "public"
db-anon-role = "anon"
jwt-secret = "change-me"
pre-request = ""
db-pool = 10
server-host = "!4"
server-port = 3000
max-rows = 1000
role-claim-key = ".role"
cors-origins = "*"

